### ISSUE TITLE
pipeline example fails on workflow machine

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.ensemblemd#115]
with:
```
================================================================================
 EnsembleMD (0.3.7)                                                             
================================================================================

Starting Allocation                                                           ok
        Verifying pattern                                                     ok
        Starting pattern execution                                            ok
--------------------------------------------------------------------------------
Executing 3 pipeline instances of 16 steps on 1 allocated core(s) on 'local.localhost'

Job waiting on queue...
Job is now running !
Waiting for step_1 to complete.                                             done
Waiting for step_2 to complete.                                             done
Waiting for step_3 to complete.                                             done
--------------------------------------------------------------------------------
Pattern execution successfully finished                                         

Starting Deallocation2015-10-21 21:33:03,659: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: SAGA job state for ComputePilot pilot.0000 is Failed.
2015-10-21 21:33:03,659: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2015-10-21 21:33:03,660: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 335, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 127, in pilot_state_cb
    sys.exit(2)
SystemExit: 2
Traceback (most recent call last):
  File "pipeline.py", line 117, in <module>
    cluster.deallocate()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 103, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/session.py", line 281, in close
    pmgr.close (terminate=terminate)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 175, in close
    self.cancel_pilots()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 566, in cancel_pilots
    self._worker.register_cancel_pilots_request(pilot_ids=pilot_ids)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 601, in register_cancel_pilots_request
    time.sleep(0.3)
KeyboardInterrupt
```

**Comment by vivek-bala** [comment]
Can you rerun this and see if it repeats ? The error seems to be during dellocation (shutdown). You can run it with RADICAL_ENMD_VERBOSE=debug RADICAL_PILOT_VERBOSE=debug incase the failure is during the steps.

**Comment by antonst** [comment]
>The error seems to be during dellocation (shutdown)

Yes, It seems to finish, but fails during deallocation

**Comment by vivek-bala** [comment]
I am not sure why, but I have been noticing shutdown issues on the workflow machine. I don't see this on  my machine though.

**Comment by antonst** [comment]
With RADICAL_ENMD_VERBOSE=debug it did not produce any errors and now with export RADICAL_ENMD_VERBOSE=REPORT worked as well. I have no idea what happened.

**Comment by antonst** [comment]
yes at a third attempt produces error as well:
```
Pattern execution successfully finished                                         

Starting Deallocation2015-10-21 22:07:37,580: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: SAGA job state for ComputePilot pilot.0000 is Failed.
2015-10-21 22:07:37,580: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2015-10-21 22:07:37,580: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 335, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 127, in pilot_state_cb
    sys.exit(2)
SystemExit: 2
Traceback (most recent call last):
  File "pipeline.py", line 117, in <module>
    cluster.deallocate()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 103, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/session.py", line 281, in close
    pmgr.close (terminate=terminate)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 184, in close
    self._worker.cancel_launcher()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 195, in cancel_launcher
    worker.stop ()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 91, in stop
    self.join()
  File "/opt/radical/lib/python2.7/threading.py", line 949, in join
    self.__block.wait()
  File "/opt/radical/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by antonst** [comment]
With debug flags output is:
```
2015-10-21 22:09:17,631: radical.enmd.pipeline.static.default: MainProcess                     : MainThread     : DEBUG   : Created step_2 CU: {'kernel': None, 'executable': '/bin/bash', 'name': 'step_2', 'restartable': False, 'output_staging': [{'source': 'cfreqs-3.dat', 'target': 'cfreqs-3.dat'}], 'stdout': None, 'pre_exec': [], 'mpi': False, 'environment': None, 'cleanup': False, 'arguments': ['-l', '-c', 'grep -o . asciifile-3.dat | sort | uniq -c > cfreqs-3.dat'], 'stderr': None, 'cores': 1, 'post_exec': None, 'input_staging': [{'action': 'Link', 'source': '/home/antontre/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.antontre.016730.0004-pilot.0000/unit.000002/asciifile-3.dat', 'target': 'asciifile-3.dat'}]}.
2015-10-21 22:09:17,631: radical.enmd.pipeline.static.default: MainProcess                     : MainThread     : INFO    : Submitted tasks for step_2.
2015-10-21 22:09:33,440: radical.enmd.misc.chksum: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.10 (default, Oct 19 2015, 13:07:33) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
2015-10-21 22:09:33,442: radical.enmd.misc.chksum: MainProcess                     : MainThread     : INFO    :                      pid: 1752808
2015-10-21 22:09:33,442: radical.enmd.misc.chksum: MainProcess                     : MainThread     : INFO    :                      tid: MainThread
2015-10-21 22:09:33,489: radical.enmd.pipeline.static.default: MainProcess                     : MainThread     : DEBUG   : Created step_3 CU: {'kernel': None, 'executable': '/bin/bash', 'name': 'step_3', 'restartable': False, 'output_staging': [{'source': 'cfreqs-3.sha1', 'target': 'cfreqs-3.sha1'}], 'stdout': None, 'pre_exec': ['command -v sha1sum >/dev/null 2>&1 && export SHASUM=sha1sum  || export SHASUM=shasum'], 'mpi': False, 'environment': None, 'cleanup': False, 'arguments': ['-l', '-c', '$SHASUM cfreqs-3.dat > cfreqs-3.sha1'], 'stderr': None, 'cores': 1, 'post_exec': None, 'input_staging': [{'action': 'Link', 'source': '/home/antontre/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.antontre.016730.0004-pilot.0000/unit.000005/cfreqs-3.dat', 'target': 'cfreqs-3.dat'}]}.
2015-10-21 22:09:33,490: radical.enmd.pipeline.static.default: MainProcess                     : MainThread     : INFO    : Submitted tasks for step_3.
2015-10-21 22:09:38,307: radical.enmd.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Deallocating Cluster
2015-10-21 22:09:42,039: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource local.localhost state has changed to Canceled
2015-10-21 22:09:43,284: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource local.localhost state has changed to Failed
2015-10-21 22:09:43,285: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: SAGA job state for ComputePilot pilot.0000 is Failed.
2015-10-21 22:09:43,285: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2015-10-21 22:09:43,285: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 335, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 127, in pilot_state_cb
    sys.exit(2)
SystemExit: 2
Traceback (most recent call last):
  File "pipeline.py", line 117, in <module>
    cluster.deallocate()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 103, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/session.py", line 281, in close
    pmgr.close (terminate=terminate)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 184, in close
    self._worker.cancel_launcher()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 195, in cancel_launcher
    worker.stop ()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 91, in stop
    self.join()
  File "/opt/radical/lib/python2.7/threading.py", line 949, in join
    self.__block.wait()
  File "/opt/radical/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt

```

**Comment by vivek-bala** [comment]
```
2015-10-21 22:09:42,039: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource local.localhost state has changed to Canceled
2015-10-21 22:09:43,284: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource local.localhost state has changed to Failed
2015-10-21 22:09:43,285: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: SAGA job state for ComputePilot pilot.0000 is Failed.
2015-10-21 22:09:43,285: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
```

Double shutdown attempt ? I ran into this in one of the RP 0.37.? versions.

**Comment by andre-merzky** [comment]
Yes, likely an RP level problem: a cancelled pilot is sometimes reported as FAILED, which then rtiggers a callback on your end...
