### ISSUE TITLE
getting_started.py unclean shut down

### ISSUE THREAD

**Issue by shantenujha** [radical-cybertools/radical.ensemblemd#116]
Starting Deallocation2015-10-21 23:25:56,520: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: Could not reconnect to pilot pilot.0000 multiple times - giving up
2015-10-21 23:25:56,522: radical.enmd.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2015-10-21 23:25:56,523: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : pilot manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/jha/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 335, in run
    self.call_callbacks(pilot_id, new_state)
  File "/home/jha/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/jha/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 127, in pilot_state_cb
    sys.exit(2)
SystemExit: 2

Traceback (most recent call last):
  File "share/radical.ensemblemd/user_guide/scripts/get_started.py", line 64, in <module>
    cluster.deallocate()
  File "/home/jha/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 103, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/jha/myenv/lib/python2.7/site-packages/radical/pilot/session.py", line 281, in close
    pmgr.close (terminate=terminate)
  File "/home/jha/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 175, in close
    self.cancel_pilots()
  File "/home/jha/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 566, in cancel_pilots
    self._worker.register_cancel_pilots_request(pilot_ids=pilot_ids)
  File "/home/jha/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 601, in register_cancel_pilots_request
    time.sleep(0.3)
KeyboardInterrupt

**Comment by andre-merzky** [comment]
Yes, I have seen that, too.  I'll explain this   to the students during the tutorial...
