### ISSUE TITLE
ValueError: I/O operation on closed file

### ISSUE THREAD

**Issue by suvigya91** [radical-cybertools/radical.ensemblemd#127]
Hi, 
I am trying to write test case for Execution Context Api to allocate resource. As soon as allocate() is called I get following exception:

```
Exception in thread PilotLauncherWorker-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/radical.pilot-0.38-py2.7.egg/radical/pilot/controller/pilot_launcher_worker.py", line 861, in run
    logger.exception ('\n'.join (log_messages))
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/radical.utils-0.38-py2.7.egg/radical/utils/logger.py", line 67, in emit
    self.stream.write(self.format(record) + self._term)
  File "/usr/lib/python2.7/dist-packages/py/_io/capture.py", line 131, in write
    self._stream.write(obj)
ValueError: I/O operation on closed file

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/radical.pilot-0.38-py2.7.egg/radical/pilot/controller/pilot_manager_controller.py", line 342, in run
    self.call_callbacks(pilot_id, new_state)
  File "/usr/local/lib/python2.7/dist-packages/radical.pilot-0.38-py2.7.egg/radical/pilot/controller/pilot_manager_controller.py", line 262, in call_callbacks
    logger.exception("Couldn't call callback function %s" % e)
  File "/usr/lib/python2.7/logging/__init__.py", line 1185, in exception
    self.error(msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1178, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1271, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1281, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1321, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/local/lib/python2.7/dist-packages/radical.utils-0.38-py2.7.egg/radical/utils/logger.py", line 67, in emit
    self.stream.write(self.format(record) + self._term)
  File "/usr/lib/python2.7/dist-packages/py/_io/capture.py", line 131, in write
    self._stream.write(obj)
ValueError: I/O operation on closed file
```

 Please Help! Here is the sample test case:

```
    import os
    import sys
    import json
    import pytest
    import radical.ensemblemd

    from radical.ensemblemd.exceptions import TypeError
    from radical.ensemblemd import Kernel
    from radical.ensemblemd import Pipeline
    from radical.ensemblemd import SingleClusterEnvironment
    from radical.ensemblemd import EnsemblemdError

    db_url = "mongodb://localhost:27017/dbname"
    resource = 'local.localhost'

    #--------------------------------------------------------
    #

     def test_allocate():
        cluster = SingleClusterEnvironment(
                    resource=resource,
                    cores=1,
                    walltime=15,
                    database_url='mongodb://localhost:27017/dbname',
                    database_name='myexps',
                  )


            # Allocate the resources.
        try:
            cluster.allocate()
            
    ##        cluster.run("wrong_type")
    ##
    ##        # Deallocate the resources. 
    ##        cluster.deallocate()
    ##
        except:
            print "Ensemble MD Toolkit Error"
     ##            pass # Just raise the execption again to get the backtrace
```

**Comment by vivek-bala** [comment]
I guess this is resolved after the meeting. please reopen if not.
