### ISSUE TITLE
multiple_simulations_multiple_analysis.py fails on stampede

### ISSUE THREAD

**Issue by georgeha** [radical-cybertools/radical.ensemblemd#132]
```
Iteration 1: Waiting for analysis tasks: misc.ccount to complete2016-05-12 20:53:49,608: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : MainThread     : INFO    : Analysis in iteration 1/kernel 1: misc.ccount completed.
            done2016-05-12 20:53:49,658: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : MainThread     : INFO    : Submitted tasks for simulation iteration 2.
2016-05-12 20:53:49,658: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : MainThread     : INFO    : Waiting for 8 simulations in iteration 2/ kernel 1: misc.mkfile to complete.

Iteration 2: Waiting for 8 simulation tasks: misc.mkfile to complete2016-05-12 20:54:06,404: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : MainThread     : INFO    : Simulations in iteration 2/ kernel 1: misc.mkfile completed.
        done2016-05-12 20:54:06,443: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : MainThread     : INFO    : Submitted tasks for analysis iteration 2.
2016-05-12 20:54:06,443: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : MainThread     : INFO    : Waiting for 8 analysis tasks in iteration 2/kernel 1: misc.ccount to complete.

Iteration 2: Waiting for analysis tasks: misc.ccount to complete2016-05-12 20:54:10,307: radical.saga.pty    : MainProcess                     : OutputFileTransferWorker-1: ERROR   : flushing failed
Traceback (most recent call last):
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py", line 676, in read
    raise e
NoSuccess: unexpected EOF (s or how to disable)

   Would you like to know how much memory your code uses during execution? Try TACC's remora tool:
     $ module load remora
     $ module help remora

login4.stampede(1)$ $$PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->) (/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py +606 (read)  :  raise se.NoSuccess ("unexpected EOF (%s)" % self.tail))
2016-05-12 20:54:10,384: radical.pilot       : MainProcess                     : OutputFileTransferWorker-1: ERROR   : Output transfer failed: unexpected EOF (s or how to disable)

   Would you like to know how much memory your code uses during execution? Try TACC's remora tool:
     $ module load remora
     $ module help remora

login4.stampede(1)$ $$PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->) (/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py +606 (read)  :  raise se.NoSuccess ("unexpected EOF (%s)" % self.tail))
Traceback (most recent call last):
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/radical/pilot/controller/output_file_transfer_worker.py", line 147, in run
    session=self._session)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/filesystem/file.py", line 86, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1014, in init_instance
    self.initialize ()
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1055, in initialise
    ret, out, _ = self.shell.obj.run_sync (cmd)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 637, in run_sync
    self.pty_shell.flush ()
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py", line 676, in read
    raise e
NoSuccess: unexpected EOF (s or how to disable)

   Would you like to know how much memory your code uses during execution? Try TACC's remora tool:
     $ module load remora
     $ module help remora

login4.stampede(1)$ $$PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->) (/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py +606 (read)  :  raise se.NoSuccess ("unexpected EOF (%s)" % self.tail))
Exception in thread OutputFileTransferWorker-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/radical/pilot/controller/output_file_transfer_worker.py", line 147, in run
    session=self._session)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/filesystem/file.py", line 86, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1014, in init_instance
    self.initialize ()
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 1055, in initialise
    ret, out, _ = self.shell.obj.run_sync (cmd)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 637, in run_sync
    self.pty_shell.flush ()
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py", line 676, in read
    raise e
NoSuccess: unexpected EOF (s or how to disable)

   Would you like to know how much memory your code uses during execution? Try TACC's remora tool:
     $ module load remora
     $ module help remora

login4.stampede(1)$ $$PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->PROMPT-0->) (/Users/giorgos/vivek-tests/lib/python2.7/site-packages/saga/utils/pty_process.py +606 (read)  :  raise se.NoSuccess ("unexpected EOF (%s)" % self.tail))

2016-05-12 20:54:13,065: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : ComputeUnit error: STDERR: grep: asciifile.dat: No such file or directory
, STDOUT: grep: asciifile.dat: No such file or directory

2016-05-12 20:54:13,065: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : Pattern execution FAILED.
2016-05-12 20:54:13,065: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 262, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 199, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 318, in unit_state_cb
    sys.exit(1)
SystemExit: 1
Execution interuptedTraceback (most recent call last):
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 622, in execute_pattern
    resource._umgr.wait_units(bids)
  File "/Users/giorgos/vivek-tests/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 698, in wait_units
    time.sleep (0.5)
KeyboardInterrupt

Starting Deallocation..
2016-05-12 20:54:13,255: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Deallocating Cluster
2016-05-12 20:54:26,367: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.stampede state has changed to Canceled
2016-05-12 20:54:26,367: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource allocation cancelled.
Resource allocation cancelled.                                              done 
```

**Comment by georgeha** [comment]
Well, I run this example again and it worked. It seems that I encountered this error because I tried to run another job on stampede concurrently with this one

**Comment by vivek-bala** [comment]
So this can be closed, right ?
