### ISSUE TITLE
bag_of_tasks.py example fails on Stampede

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.ensemblemd#140]
with:
```
================================================================================
 EnsembleMD (0.4-RC0)                                                           
================================================================================

Starting Allocation2016-05-13 18:36:51,048: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : prompted for unknown password (Warning: Permanently added the RSA host key for IP address '129.114.62.12' to the list of known hosts.
Password: ) (/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match))
Traceback (most recent call last):
  File "/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 313, in _initialize_pty
    % match)
AuthenticationFailed: prompted for unknown password (Warning: Permanently added the RSA host key for IP address '129.114.62.12' to the list of known hosts.
Password: ) (/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match))
2016-05-13 18:36:51,049: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during resource allocation: prompted for unknown password (Warning: Permanently added the RSA host key for IP address '129.114.62.12' to the list of known hosts.
Password: ) (/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match)).
Traceback (most recent call last):
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 232, in allocate
    self._pilot = pmgr.submit_pilots(pdesc)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 361, in submit_pilots
    resource_config=resource_cfg)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 433, in register_start_pilot_request
    shell = sup.PTYShell(url, self._session)
  File "/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 244, in __init__
    posix=self.posix)
  File "/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 196, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 411, in _initialize_pty
    raise ptye.translate_exception (e)
AuthenticationFailed: prompted for unknown password (Warning: Permanently added the RSA host key for IP address '129.114.62.12' to the list of known hosts.
Password: ) (/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match))
Allocation failed: prompted for unknown password (Warning: Permanently added the RSA host key for IP address '129.114.62.12' to the list of known hosts.
Password: ) (/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match))Traceback (most recent call last):
  File "bag_of_tasks.py", line 82, in <module>
    cluster.allocate()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 232, in allocate
    self._pilot = pmgr.submit_pilots(pdesc)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 361, in submit_pilots
    resource_config=resource_cfg)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 433, in register_start_pilot_request
    shell = sup.PTYShell(url, self._session)
  File "/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 244, in __init__
    posix=self.posix)
  File "/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 196, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 411, in _initialize_pty
    raise ptye.translate_exception (e)
saga.exceptions.AuthenticationFailed: prompted for unknown password (Warning: Permanently added the RSA host key for IP address '129.114.62.12' to the list of known hosts.
Password: ) (/home/antontre/myenv/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +313 (_initialize_pty)  :  % match))
```

**Comment by andre-merzky** [comment]
`prompted for unknown password`

Some ssh setup problem?

**Comment by antonst** [comment]
how did I manage to run previous examples on Stampede then?

**Comment by antonst** [comment]
The only difference is that instead of ```xsede.stampede``` I have used ```stampede.tacc.utexas.edu``` as suggested in documentation.

**Comment by andre-merzky** [comment]
Hmm, I am not sure how that setting differs on the RP layer.  Vivek?

**Comment by vivek-bala** [comment]
in config.json we have ```xsede.stampede``` key which picks 'gsissh'. That's why this is popping up.

**Comment by vivek-bala** [comment]
I think the docs might be using stampede.tacc.utexas.edu. let me fix that in RTD.

**Comment by vivek-bala** [comment]
Fixed RTD with "xsede.stampede".
