### ISSUE TITLE
Error running adaptive_simulation_analysis_loop.py on Comet

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.ensemblemd#163]
When running `adaptive_simulation_analysis_loop.py` on Comet, I get the following error during the execution of the first iteration. The error message is as follows:

```
(ve_entk)[mingtha@workflow examples]$ python adaptive_simulation_analysis_loop.py xsede.comet

================================================================================
 EnsembleMD (0.4.3-8-g7aac053)                                                  
================================================================================

Starting Allocation                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing simulation-analysis loop with 2 iterations on 1 allocated core(s) on 'xsede.comet'

Job waiting on queue...
Job is now running !
Iteration 1: Waiting for 16 simulation tasks: misc.mkfile to complete2016-07-13 15:23:48,479: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : ComputeUnit error: STDERR: ssh_exchange_identification: Connection closed by remote host
, STDOUT: ssh_exchange_identification: Connection closed by remote host

2016-07-13 15:23:48,479: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : Pattern execution FAILED.
2016-07-13 15:23:48,480: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 262, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 199, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 318, in unit_state_cb
    sys.exit(1)
SystemExit: 1
Execution interuptedTraceback (most recent call last):
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 512, in execute_pattern
    resource._umgr.wait_units(uids)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 698, in wait_units
    time.sleep (0.5)
KeyboardInterrupt

Starting Deallocation..
Resource allocation cancelled. 
```

**Comment by vivek-bala** [comment]
Comet specific: https://github.com/radical-cybertools/radical.pilot/issues/1033

**Comment by mingtaiha** [comment]
Works now with new RP tutorial-xsede16 branch and new RP MongoDB Url
