### ISSUE TITLE
Connection closed by remote host (multiple_simulaitons_single_analysis.py)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.ensemblemd#164]
I get the following error when I run the script `multiple_simulations_single_analysis.py`, which is very reminiscent of [#151](https://github.com/radical-cybertools/radical.ensemblemd/issues/151)

```
(ve_entk)[mingtha@workflow examples]$ python multiple_simulations_single_analysis.py xsede.comet

================================================================================
 EnsembleMD (0.4.3-8-g7aac053)                                                  
================================================================================

Starting Allocation                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing simulation-analysis loop with 4 iterations on 1 allocated core(s) on 'xsede.comet'

Job waiting on queue...
Job is now running !
Iteration 1: Waiting for 16 simulation tasks: misc.mkfile to complete2016-07-13 15:38:52,011: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : ComputeUnit error: STDERR: ssh_exchange_identification: Connection closed by remote host
, STDOUT: ssh_exchange_identification: Connection closed by remote host

2016-07-13 15:38:52,011: radical.entk.simulation_analysis_loop.static.default: MainProcess                     : Thread-3       : ERROR   : Pattern execution FAILED.
2016-07-13 15:38:52,011: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 262, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 199, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 318, in unit_state_cb
    sys.exit(1)
SystemExit: 1
Execution interuptedTraceback (most recent call last):
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 512, in execute_pattern
    resource._umgr.wait_units(uids)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 698, in wait_units
    time.sleep (0.5)
KeyboardInterrupt

Starting Deallocation..
Resource allocation cancelled.
```

**Comment by mingtaiha** [comment]
Ran this again with update to RP tutorial-xsede16 branch with the RP MongoDB (whose link I will not post ;P)
