### ISSUE TITLE
failed pilot, no clear indication

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.ensemblemd#20]
Pilot failed for good reasons, this is more about the error handling.

```
$ python bag.py 
Traceback (most recent call last):
  File "bag.py", line 29, in <module>
    cluster.run(app)
  File "/Users/mark/EnMDToolkit/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 67, in run
    plugin.execute_pattern(pattern, self)
  File "/Users/mark/EnMDToolkit/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/pipeline/static.py", line 229, in execute_pattern
    raise EnsemblemdError("One or more ComputeUnits failed in pipeline step {0}: \n{1}".format(step, failed_units))
radical.ensemblemd.exceptions.EnsemblemdError: One or more ComputeUnits failed in pipeline step 1: 
 * Compute Unit 54b832d5a85378539fe1ee00 failed with an error: None

```

**Comment by oleweidner** [comment]
ole to double-check

**Comment by oleweidner** [comment]
Fixed to the extend possible.
