### ISSUE TITLE
Repex pattern b fails on localhost, stampede

### ISSUE THREAD

**Issue by vivek-bala** [radical-cybertools/radical.ensemblemd#32]
Localhost verbose op :-
```
$ python replica_exchange_b.py 
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ] Loading execution plug-ins...
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'pipeline.static.default' from radical.ensemblemd.exec_plugins.pipeline.static
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'simulation_analysis_loop.static.default' from radical.ensemblemd.exec_plugins.simulation_analysis_loop.static
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'replica_exchange.static_pattern_1' from radical.ensemblemd.exec_plugins.replica_exchange.static_pattern_1
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'replica_exchange.static_pattern_2' from radical.ensemblemd.exec_plugins.replica_exchange.static_pattern_2
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'allpairs.static.default' from radical.ensemblemd.exec_plugins.allpairs.static
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ] Loading kernel plug-ins...
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.pre_coam_loop' from radical.ensemblemd.kernel_plugins.md.pre_coam_loop
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.amber' from radical.ensemblemd.kernel_plugins.md.amber
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.coco' from radical.ensemblemd.kernel_plugins.md.coco
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.mmpbsa' from radical.ensemblemd.kernel_plugins.md.mmpbsa
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.namd' from radical.ensemblemd.kernel_plugins.md.namd
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.re_exchange' from radical.ensemblemd.kernel_plugins.md.re_exchange
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.pre_grlsd_loop' from radical.ensemblemd.kernel_plugins.md.pre_grlsd_loop
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.gromacs' from radical.ensemblemd.kernel_plugins.md.gromacs
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.pre_lsdmap' from radical.ensemblemd.kernel_plugins.md.pre_lsdmap
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.lsdmap' from radical.ensemblemd.kernel_plugins.md.lsdmap
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.post_lsdmap' from radical.ensemblemd.kernel_plugins.md.post_lsdmap
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.nop' from radical.ensemblemd.kernel_plugins.misc.nop
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.mkfile' from radical.ensemblemd.kernel_plugins.misc.mkfile
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.ccount' from radical.ensemblemd.kernel_plugins.misc.ccount
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.chksum' from radical.ensemblemd.kernel_plugins.misc.chksum
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.levenshtein' from radical.ensemblemd.kernel_plugins.misc.levenshtein
2015:01:21 11:57:25 10632  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.diff' from radical.ensemblemd.kernel_plugins.misc.diff
2015:01:21 11:57:26 10632  MainThread   radical.enmd.SingleClusterEnvironment: [INFO    ] Requesting resources on localhost
2015:01:21 11:57:26 10632  MainThread   radical.enmd.SingleClusterEnvironment: [INFO    ] Launched 1-core pilot on localhost.
2015:01:21 11:57:26 10632  MainThread   radical.enmd.Engine   : [INFO    ] Selected execution plug-in 'replica_exchange.static_pattern_2' for pattern 'ReplicaExchange' and context type 'Static'.
2015:01:21 11:57:27 10632  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource localhost state has changed to Launching
2015:01:21 11:57:28 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 0
2015:01:21 11:57:28 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 0 for MD run
2015:01:21 11:57:28 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 1
2015:01:21 11:57:28 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 1 for MD run
2015:01:21 11:57:29 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 2
2015:01:21 11:57:29 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 2 for MD run
2015:01:21 11:57:29 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 3
2015:01:21 11:57:29 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 3 for MD run
2015:01:21 11:57:29 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 4
2015:01:21 11:57:29 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 4 for MD run
2015:01:21 11:57:30 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 5
2015:01:21 11:57:30 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 5 for MD run
2015:01:21 11:57:30 10632  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource localhost state has changed to PendingActive
2015:01:21 11:57:30 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 6
2015:01:21 11:57:30 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 6 for MD run
2015:01:21 11:57:30 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 7
2015:01:21 11:57:30 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 7 for MD run
2015:01:21 11:57:31 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 8
2015:01:21 11:57:31 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 8 for MD run
2015:01:21 11:57:31 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 9
2015:01:21 11:57:31 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 9 for MD run
2015:01:21 11:57:31 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 10
2015:01:21 11:57:31 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 10 for MD run
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 11
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 11 for MD run
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 12
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 12 for MD run
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 13
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 13 for MD run
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 14
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 14 for MD run
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 15
2015:01:21 11:57:32 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 15 for MD run
2015:01:21 11:57:33 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Performing MD step for replicas
2015:01:21 11:57:43 10632  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource localhost state has changed to Active
2015:01:21 11:58:00 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 0 for Exchange run
2015:01:21 11:58:00 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 1 for Exchange run
2015:01:21 11:58:01 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 2 for Exchange run
2015:01:21 11:58:01 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 3 for Exchange run
2015:01:21 11:58:01 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 4 for Exchange run
2015:01:21 11:58:02 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 5 for Exchange run
2015:01:21 11:58:02 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 6 for Exchange run
2015:01:21 11:58:02 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 7 for Exchange run
2015:01:21 11:58:02 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 8 for Exchange run
2015:01:21 11:58:02 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 9 for Exchange run
2015:01:21 11:58:02 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 10 for Exchange run
2015:01:21 11:58:03 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 11 for Exchange run
2015:01:21 11:58:03 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 12 for Exchange run
2015:01:21 11:58:03 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 13 for Exchange run
2015:01:21 11:58:03 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 14 for Exchange run
2015:01:21 11:58:03 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 15 for Exchange run
2015:01:21 11:58:04 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Performing Exchange step for replicas
2015:01:21 12:27:44 10632  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource localhost state has changed to Done
2015:01:21 12:27:45 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Composing swap matrix
2015:01:21 12:27:45 10632  MainThread   radical.enmd.replica_exchange.static_pattern_2: [ERROR   ] Fatal error during execution: could not convert string to float: None.
Traceback (most recent call last):
  File "/home/vivek/Research/enmd-test/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 169, in execute_pattern
    swap_matrix = pattern.get_swap_matrix(replicas, matrix_columns)
  File "replica_exchange_b.py", line 275, in get_swap_matrix
    swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
ValueError: could not convert string to float: None
Traceback (most recent call last):
  File "replica_exchange_b.py", line 318, in <module>
    cluster.run(re_pattern, force_plugin="replica_exchange.static_pattern_2")
  File "/home/vivek/Research/enmd-test/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 172, in run
    plugin.execute_pattern(pattern, self)
  File "/home/vivek/Research/enmd-test/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 169, in execute_pattern
    swap_matrix = pattern.get_swap_matrix(replicas, matrix_columns)
  File "replica_exchange_b.py", line 275, in get_swap_matrix
    swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
ValueError: could not convert string to float: None

```

The script remains in the exchange state for ~30 mins which is the walltime. 

Stampede verbose op :-

```
$ python replica_exchange_b.py 
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ] Loading execution plug-ins...
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'pipeline.static.default' from radical.ensemblemd.exec_plugins.pipeline.static
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'simulation_analysis_loop.static.default' from radical.ensemblemd.exec_plugins.simulation_analysis_loop.static
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'replica_exchange.static_pattern_1' from radical.ensemblemd.exec_plugins.replica_exchange.static_pattern_1
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'replica_exchange.static_pattern_2' from radical.ensemblemd.exec_plugins.replica_exchange.static_pattern_2
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded execution plug-in 'allpairs.static.default' from radical.ensemblemd.exec_plugins.allpairs.static
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ] Loading kernel plug-ins...
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.pre_coam_loop' from radical.ensemblemd.kernel_plugins.md.pre_coam_loop
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.amber' from radical.ensemblemd.kernel_plugins.md.amber
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.coco' from radical.ensemblemd.kernel_plugins.md.coco
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.mmpbsa' from radical.ensemblemd.kernel_plugins.md.mmpbsa
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.namd' from radical.ensemblemd.kernel_plugins.md.namd
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.re_exchange' from radical.ensemblemd.kernel_plugins.md.re_exchange
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.pre_grlsd_loop' from radical.ensemblemd.kernel_plugins.md.pre_grlsd_loop
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.gromacs' from radical.ensemblemd.kernel_plugins.md.gromacs
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.pre_lsdmap' from radical.ensemblemd.kernel_plugins.md.pre_lsdmap
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.lsdmap' from radical.ensemblemd.kernel_plugins.md.lsdmap
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'md.post_lsdmap' from radical.ensemblemd.kernel_plugins.md.post_lsdmap
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.nop' from radical.ensemblemd.kernel_plugins.misc.nop
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.mkfile' from radical.ensemblemd.kernel_plugins.misc.mkfile
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.ccount' from radical.ensemblemd.kernel_plugins.misc.ccount
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.chksum' from radical.ensemblemd.kernel_plugins.misc.chksum
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.levenshtein' from radical.ensemblemd.kernel_plugins.misc.levenshtein
2015:01:21 12:49:17 13797  MainThread   radical.enmd.Engine   : [INFO    ]  > Loaded kernel plug-in 'misc.diff' from radical.ensemblemd.kernel_plugins.misc.diff
2015:01:21 12:49:17 13797  MainThread   radical.enmd.SingleClusterEnvironment: [INFO    ] Requesting resources on stampede.tacc.utexas.edu
2015:01:21 12:49:24 13797  MainThread   radical.enmd.SingleClusterEnvironment: [INFO    ] Launched 16-core pilot on stampede.tacc.utexas.edu.
2015:01:21 12:49:24 13797  MainThread   radical.enmd.Engine   : [INFO    ] Selected execution plug-in 'replica_exchange.static_pattern_2' for pattern 'ReplicaExchange' and context type 'Static'.
2015:01:21 12:49:24 13797  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource stampede.tacc.utexas.edu state has changed to Launching
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 0
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 0 for MD run
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 1
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 1 for MD run
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 2
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 2 for MD run
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 3
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 3 for MD run
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 4
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 4 for MD run
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 5
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 5 for MD run
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 6
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 6 for MD run
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 7
2015:01:21 12:49:36 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 7 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 8
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 8 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 9
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 9 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 10
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 10 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 11
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 11 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 12
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 12 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 13
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 13 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 14
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 14 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Building input files for replica 15
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 15 for MD run
2015:01:21 12:49:37 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Performing MD step for replicas
2015:01:21 12:49:45 13797  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource stampede.tacc.utexas.edu state has changed to PendingActive
2015:01:21 12:51:00 13797  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource stampede.tacc.utexas.edu state has changed to Active
2015:01:21 12:51:15 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 0 for Exchange run
2015:01:21 12:51:15 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 1 for Exchange run
2015:01:21 12:51:16 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 2 for Exchange run
2015:01:21 12:51:16 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 3 for Exchange run
2015:01:21 12:51:16 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 4 for Exchange run
2015:01:21 12:51:16 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 5 for Exchange run
2015:01:21 12:51:16 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 6 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 7 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 8 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 9 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 10 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 11 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 12 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 13 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 14 for Exchange run
2015:01:21 12:51:17 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Preparing replica 15 for Exchange run
2015:01:21 12:51:18 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Performing Exchange step for replicas
2015:01:21 13:21:21 13797  Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource stampede.tacc.utexas.edu state has changed to Failed
2015:01:21 13:21:21 13797  Thread-1     radical.enmd.SingleClusterEnvironment: [ERROR   ] Resource error: SAGA job state for ComputePilot 54bfe69d2330e035e58d92ff is Canceled.
2015:01:21 13:21:21 13797  Thread-1     radical.enmd.SingleClusterEnvironment: [ERROR   ] Pattern execution FAILED.
2015:01:21 13:21:22 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Composing swap matrix
2015:01:21 13:21:22 13797  MainThread   radical.enmd.replica_exchange.static_pattern_2: [ERROR   ] Fatal error during execution: could not convert string to float: None.
Traceback (most recent call last):
  File "/home/vivek/Research/enmd-test/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 169, in execute_pattern
    swap_matrix = pattern.get_swap_matrix(replicas, matrix_columns)
  File "replica_exchange_b.py", line 275, in get_swap_matrix
    swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
ValueError: could not convert string to float: None
Traceback (most recent call last):
  File "replica_exchange_b.py", line 320, in <module>
    cluster.run(re_pattern, force_plugin="replica_exchange.static_pattern_2")
  File "/home/vivek/Research/enmd-test/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 172, in run
    plugin.execute_pattern(pattern, self)
  File "/home/vivek/Research/enmd-test/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 169, in execute_pattern
    swap_matrix = pattern.get_swap_matrix(replicas, matrix_columns)
  File "replica_exchange_b.py", line 275, in get_swap_matrix
    swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
ValueError: could not convert string to float: None

```
Am I missing something ? The script is similar to the one provided in the documentation. Only changes were to the number of cycles and resource descriptions.

**Comment by AntonsT** [comment]
I can't figure out from the logs you have provided here that is going on apart from the fact that matrix doesn't get populated properly. Can you please re-run examples with RADICAL_PILOT_VERBOSE=debug? Also, logs for localhost and stampede are essentially the same, so there was no need to include both. Am I missing something? Can you please next time create gists for logs and only provide links here? Text from logs does not fit into message window here and it is difficult to read.

Thanks,
Antons

**Comment by AntonsT** [comment]
Vivek, I have just re-run this example and it works for me (master branch):
>git clone https://github.com/radical-cybertools/radical.ensemblemd.git
cd radical.ensemblemd
git checkout master
python setup.py install

**Comment by vivek-bala** [comment]
Yup works now. Had to make a fresh installation. I get an error while enabling profiling,

```
Ensemble MD Toolkit Error: RADICAL_ENMD_PROFILING set but profiling is not implemented for this pattern yet.
Traceback (most recent call last):
  File "replica_exchange_b.py", line 318, in <module>
    cluster.run(re_pattern, force_plugin="replica_exchange.static_pattern_2")
  File "/home/vivek/Research/enmd-test/myenv/local/lib/python2.7/site-packages/radical.ensemblemd-0.2_rc4_10_g3ea45ee-py2.7.egg/radical/ensemblemd/single_cluster_environment.py", line 171, in run
    plugin.verify_pattern(pattern, self)
  File "/home/vivek/Research/enmd-test/myenv/local/lib/python2.7/site-packages/radical.ensemblemd-0.2_rc4_10_g3ea45ee-py2.7.egg/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 53, in verify_pattern
    raise EnsemblemdError("RADICAL_ENMD_PROFILING set but profiling is not implemented for this pattern yet.")
radical.ensemblemd.exceptions.EnsemblemdError: RADICAL_ENMD_PROFILING set but profiling is not implemented for this pattern yet.
```
Is this expected ?

**Comment by vivek-bala** [comment]
Antons, with the installation procedure you suggested
```
git clone https://github.com/radical-cybertools/radical.ensemblemd.git
cd radical.ensemblemd
git checkout master
python setup.py install
```

I get the same error again : https://gist.github.com/vivek-bala/5e2bcbef75ec741d87e9 (I cloned the repository again, made a fresh virtualenv). Although, it worked yesterday when I tried it right after your comment.
