### ISSUE TITLE
CDI usecase with 1024 replicas fails on stampede with:

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#43]
2015:02:17 09:10:37 7892   MainThread   radical.enmd.replica_exchange.static_pattern_2: [ERROR   ] Fatal error during execution: could not convert string to float: None.
Traceback (most recent call last):
  File "/home/treikalis/v8/lib/python2.7/site-packages/radical.ensemblemd-0.2_5_ge4f74b4-py2.7.egg/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 198, in execute_pattern
    swap_matrix = pattern.get_swap_matrix(replicas, matrix_columns)
  File "replica_exchange_mode_1.py", line 294, in get_swap_matrix
    swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
ValueError: could not convert string to float: None
Traceback (most recent call last):
  File "replica_exchange_mode_1.py", line 407, in <module>
    cluster.run(re_pattern, force_plugin="replica_exchange.static_pattern_2")
  File "/home/treikalis/v8/lib/python2.7/site-packages/radical.ensemblemd-0.2_5_ge4f74b4-py2.7.egg/radical/ensemblemd/single_cluster_environment.py", line 174, in run
    plugin.execute_pattern(pattern, self)
  File "/home/treikalis/v8/lib/python2.7/site-packages/radical.ensemblemd-0.2_5_ge4f74b4-py2.7.egg/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 198, in execute_pattern
    swap_matrix = pattern.get_swap_matrix(replicas, matrix_columns)
  File "replica_exchange_mode_1.py", line 294, in get_swap_matrix
    swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
ValueError: could not convert string to float: None
2015:02:17 13:20:39 7892   Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource stampede.tacc.utexas.edu state has changed to Failed
2015:02:17 13:20:39 7892   Thread-1     radical.enmd.SingleClusterEnvironment: [ERROR   ] Resource error: SAGA job state for ComputePilot 54e2da1d23769c1ed447af1c is Canceled.
2015:02:17 13:20:39 7892   Thread-1     radical.enmd.SingleClusterEnvironment: [ERROR   ] Pattern execution FAILED.

**Comment by vivek-bala** [comment]
I got this error with 32 replicas as well : https://gist.github.com/vivek-bala/36c9c39d1b0da7aacdca
