### ISSUE TITLE
CDI Use-Case: swap matrix calcuation error: list index out of range

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.ensemblemd#54]
Running `RADICAL_ENMD_VERBOSE=info python replica_exchange_mode_1.py` on stampde results in the following error:

```
2015:02:18 22:31:50 33916  MainThread   radical.enmd.replica_exchange.static_pattern_2: [INFO    ] Cycle 1: Composing swap matrix
2015:02:18 22:31:50 33916  MainThread   radical.enmd.replica_exchange.static_pattern_2: [ERROR   ] Fatal error during execution: list index out of range.
Traceback (most recent call last):
  File "/tmp/enmdt/lib/python2.7/site-packages/radical.ensemblemd-0.2_37_ge0653ca-py2.7.egg/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 198, in execute_pattern
    swap_matrix = pattern.get_swap_matrix(replicas, matrix_columns)
  File "replica_exchange_mode_1.py", line 314, in get_swap_matrix
    swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
IndexError: list index out of range
Traceback (most recent call last):
  File "replica_exchange_mode_1.py", line 418, in <module>
    cluster.run(re_pattern, force_plugin="replica_exchange.static_pattern_2")
  File "/tmp/enmdt/lib/python2.7/site-packages/radical.ensemblemd-0.2_37_ge0653ca-py2.7.egg/radical/ensemblemd/single_cluster_environment.py", line 177, in run
    plugin.execute_pattern(pattern, self)
  File "/tmp/enmdt/lib/python2.7/site-packages/radical.ensemblemd-0.2_37_ge0653ca-py2.7.egg/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 198, in execute_pattern
    swap_matrix = pattern.get_swap_matrix(replicas, matrix_columns)
  File "replica_exchange_mode_1.py", line 314, in get_swap_matrix
    swap_matrix[i][r.id] = float(matrix_columns[r.id][i])
IndexError: list index out of range
```

**Comment by AntonsT** [comment]
Same as 43?
