### ISSUE TITLE
Simulation-Analysis loop example; execution_profile_dataframe: Exception in thread Thread-8

### ISSUE THREAD

**Issue by AntonsT** [radical-cybertools/radical.ensemblemd#59]
Terminal output is below (not sure if this is enmd issue):
```
     pattern_entity      value_type           lower           upper
0   simulation_step_1    pattern_step 00:00:42.623417 00:00:44.550370
1   simulation_step_1   units_stagein             NaT             NaT
2   simulation_step_1      units_exec        00:00:00 00:00:01.043000
3   simulation_step_1  units_stageout             NaT             NaT
4     analysis_step_1    pattern_step 00:00:44.550695 00:00:58.413336
5     analysis_step_1   units_stagein             NaT             NaT
6     analysis_step_1      units_exec        00:00:00 00:00:12.443000
7     analysis_step_1  units_stageout 00:00:01.537000 00:00:12.844000
8   simulation_step_2    pattern_step 00:00:58.413829 00:01:00.930999
9   simulation_step_2   units_stagein             NaT             NaT
10  simulation_step_2      units_exec        00:00:00 00:00:01.170000
11  simulation_step_2  units_stageout             NaT             NaT
12    analysis_step_2    pattern_step 00:01:00.931866 00:01:16.241128
13    analysis_step_2   units_stagein             NaT             NaT
14    analysis_step_2      units_exec        00:00:00 00:00:13.052000
15    analysis_step_2  units_stageout 00:00:02.743000 00:00:13.444000
16  simulation_step_3    pattern_step 00:01:16.242513 00:01:18.093698
17  simulation_step_3   units_stagein             NaT             NaT
18  simulation_step_3      units_exec        00:00:00 00:00:01.052000
19  simulation_step_3  units_stageout             NaT             NaT
20    analysis_step_3    pattern_step 00:01:18.093969 00:01:31.718591
21    analysis_step_3   units_stagein             NaT             NaT
22    analysis_step_3      units_exec        00:00:00 00:00:12.369000
23    analysis_step_3  units_stageout 00:00:01.436000 00:00:12.702000
Exception in thread Thread-8 (most likely raised during interpreter shutdown):Exception in thread Thread-9 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner

Traceback (most recent call last):  File "/home/treikalis/enmd-new/local/lib/python2.7/site-packages/saga_python-0.26-py2.7.egg/saga/adaptors/shell/shell_job.py", line 66, in run

  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner  File "/home/treikalis/enmd-new/local/lib/python2.7/site-packages/saga_python-0.26-py2.7.egg/saga/utils/pty_shell.py", line 410, in find

  File "/home/treikalis/enmd-new/local/lib/python2.7/site-packages/saga_python-0.26-py2.7.egg/saga/adaptors/shell/shell_job.py", line 66, in run  File "/home/treikalis/enmd-new/lib/python2.7/site-packages/radical.utils-0.8-py2.7.egg/radical/utils/threads.py", line 89, in __exit__

  File "/home/treikalis/enmd-new/local/lib/python2.7/site-packages/saga_python-0.26-py2.7.egg/saga/utils/pty_shell.py", line 410, in find  File "/home/treikalis/enmd-new/lib/python2.7/site-packages/radical.utils-0.8-py2.7.egg/radical/utils/threads.py", line 79, in release

  File "/home/treikalis/enmd-new/lib/python2.7/site-packages/radical.utils-0.8-py2.7.egg/radical/utils/threads.py", line 89, in __exit__  File "/usr/lib/python2.7/threading.py", line 202, in release

  File "/home/treikalis/enmd-new/lib/python2.7/site-packages/radical.utils-0.8-py2.7.egg/radical/utils/threads.py", line 79, in release<type 'exceptions.TypeError'>: 'NoneType' object is not callable

  File "/usr/lib/python2.7/threading.py", line 202, in release
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by oleweidner** [comment]
No, I think this is the regular RP shutdown issue. Profiling output looks complete.

**Comment by oleweidner** [comment]
Might be relevant for RADICAL-Pilot or SAGA-Python issue tracker?
