### ISSUE TITLE
Failing unit tests

### ISSUE THREAD

**Issue by oleweidner** [radical-cybertools/radical.ensemblemd#68]
http://ci.radical-project.org/job/EnsembleMD%20Toolkit/5/console

```
======================================================================
FAIL: Basic test of the LSDMAP kernel.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/3d17e886/virtualenvs/9e4a708a/local/lib/python2.7/site-packages/radical/ensemblemd/tests/kernels/simple_tests.py", line 123, in test__lsdmap_kernel
    assert k.arguments == ['-f','config.ini','-c','tmpha.gro','-n','out.nn','-w','weight.w'], k.arguments
AssertionError: ['lsdm.py', '-f', 'config.ini', '-c', 'tmpha.gro', '-n', 'out.nn', '-w', 'weight.w']

======================================================================
FAIL: Check if we can copy output data to a different location on the execution host - single input.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/jenkins/shiningpanda/jobs/3d17e886/virtualenvs/9e4a708a/local/lib/python2.7/site-packages/radical/ensemblemd/tests/test_copy_output_data.py", line 61, in test__copy_input_data_single
    assert "checksum.txt" in os.listdir(self._output_dir)
AssertionError
```

**Comment by oleweidner** [comment]
Fixed in  devel

**Comment by oleweidner** [comment]
http://ci.radical-project.org/job/EnsembleMD%20Toolkit/6/console
