### ISSUE TITLE
Example replica_exchange_b.py fails with devel

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.ensemblemd#76]
The replica_exchange_b.py example fails with the devel branch of EnMD.
This is the error I get:

2015:08:07 09:55:46 14792  MainThread   radical.enmd.replica_exchange.static_pattern_2: [ERROR   ] Fatal error during execution: local variable 'arguments' referenced before assignment.
Traceback (most recent call last):
  File "/home/iparask/EnMDdevelVar/local/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/replica_exchange/static_pattern_2.py", line 208, in execute_pattern
    ex_kernel._bind_to_resource(resource._resource_key)
  File "/home/iparask/EnMDdevelVar/local/lib/python2.7/site-packages/radical/ensemblemd/kernel.py", line 414, in _bind_to_resource
    self._kernel._bind_to_resource(resource_key)
  File "/home/iparask/EnMDdevelVar/local/lib/python2.7/site-packages/radical/ensemblemd/kernel_plugins/md/re_exchange.py", line 109, in _bind_to_resource
    self._arguments   = arguments
UnboundLocalError: local variable 'arguments' referenced before assignment

I run it in localhost. I think it has to do only with the re_exchange kernel, but I may miss something.

**Comment by AntonsT** [comment]
Fixed in devel
