### ISSUE TITLE
Error Running Replica-Exchange Use-case on Stampede (Queue time > Wall time)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.ensemblemd#77]
When I tried to run the Replica-Exchange Use-case on Stampede using the development queue, the status of the job stayed at 'PendingActive' (job waiting on queue). The job did not run and eventually failed as the queue time exceeded the wall-time. I have notice that there was a .radical folder in my home directory, and the agent.err gave the following output:

login1.stampede(20)$ cat agent.log
2015-08-06 17:46:40,345 - radical.pilot.agent - INFO - Using RADICAL-Utils version 0.29
2015-08-06 17:46:40,346 - radical.pilot.agent - INFO - Using RADICAL-SAGA  version 0.29
2015-08-06 17:46:40,346 - radical.pilot.agent - INFO - Using RADICAL-Pilot version 0.34 ($Id$)
2015-08-06 17:46:40,346 - radical.pilot.agent - INFO - load agent config
2015-08-06 17:46:40,346 - radical.pilot.agent - INFO - agent config not merged: [Errno 2] No such file or directory: '/home1/03662/tg829619/.radical/pilot/configs/agent.json'
2015-08-06 17:46:40,398 - radical.pilot.agent - ERROR - Error running agent: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/work/03662/tg829619/radical.pilot.sandbox/ve_stampede/rp_install/bin/radical-pilot-agent-multicore.py", line 5533, in main
    options.mongodb_auth)
  File "/work/03662/tg829619/radical.pilot.sandbox/ve_stampede/rp_install/lib/python2.7/site-packages/radical/pilot/utils/misc.py", line 198, in get_mongodb
    mongo_client = pymongo.MongoClient(mongodb_url)
  File "/work/03662/tg829619/radical.pilot.sandbox/ve_stampede/lib/python2.7/site-packages/pymongo/mongo_client.py", line 377, in __init__
    raise ConnectionFailure(str(e))
ConnectionFailure: [Errno 111] Connection refused
2015-08-06 17:46:40,403 - radical.pilot.agent - ERROR - Error running agent: [Errno 111] Connection refused
2015-08-06 17:46:40,421 - radical.pilot.agent - ERROR - cannot log error state in database!

It seems that the duplicate .radical was picked up, the agent reported and error, and the execution did not stop

**Comment by iparask** [comment]
A job does not fail if the queue time is greater than the wall time. It just waits.

Something else happened that caused the error you see there. Do you have any logs from Ensemble MD?

**Comment by vivek-bala** [comment]
So the error seems to be that there was a local copy of RP on stampede ```No such file or directory: '/home1/03662/tg829619/.radical/pilot/configs/agent.json'```. This gets picked up by the agent, but execution does not seem to stop with an error. Whether this is an enmd issue or an rp issue needs to be investigated.

**Comment by marksantcroos** [comment]
The json error is not fatal, the database connection failure is.
