### ISSUE TITLE
MSSA example fail on localhost

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.ensemblemd#78]
This is what happens with the execution of MSSA on locahost:

2015:08:07 15:27:25 2900   Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource localhost state has changed to Active
2015:08:07 15:27:29 2900   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Simulations in iteration 1/ kernel 1: misc.mkfile completed.
2015:08:07 15:27:29 2900   MainThread   radical.enmd.simulation_analysis_loop.static.default: [ERROR   ] Fatal error during execution: 'simulation_2'.
2015:08:07 15:27:29 2900   MainThread   radical.enmd.simulation_analysis_loop.static.default: [INFO    ] Deallocating resource.
2015:08:07 15:27:35 2900   Thread-1     radical.enmd.SingleClusterEnvironment: [INFO    ] Resource localhost state has changed to Canceled
Traceback (most recent call last):
  File "multiple_simulations_single_analysis.py", line 150, in <module>
    cluster.run(mssa)
  File "/home/iparask/EnMDdevelVar/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 198, in run
    plugin.execute_pattern(pattern, self)
  File "/home/iparask/EnMDdevelVar/local/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 535, in execute_pattern
    var=resolve_placeholder_vars(working_dirs, a_instance, iteration, pattern._simulation_instances, pattern._analysis_instances, "analysis", ana_step._kernel._link_input_data[i])
  File "/home/iparask/EnMDdevelVar/local/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/simulation_analysis_loop/static.py", line 75, in resolve_placeholder_vars
    return path.replace(placeholder, working_dirs['iteration_{0}'.format(iteration)]['simulation_{0}'.format(y)])
KeyError: 'simulation_2'

**Comment by vivek-bala** [comment]
This is now resolved in devel. There was an "instance_type" specification in the user script for the simulation stage.
